// RegisterApplicationCommands.hpp - Registers the slash commands of this bot.
// May 27, 2021
// Chris M.
// https://github.com/RealTimeChris

#pragma once

#include "../HelperFunctions.hpp"

namespace DiscordCoreAPI {

	class RegisterApplicationCommands : public BaseFunction {
	  public:
		RegisterApplicationCommands() {
			this->commandName = "registerapplicationcommands";
			this->helpDescription = "Registers some application commands.";
			EmbedData msgEmbed{};
			msgEmbed.setDescription("------\nEnter /RegisterApplicationCommands.\n------");
			msgEmbed.setTitle("__**Register Slash Commands Usage:**__");
			msgEmbed.setTimeStamp(getTimeAndDate());
			msgEmbed.setColor("FeFeFe");
			this->helpEmbed = msgEmbed;
		}

		std::unique_ptr<BaseFunction> create() {
			return std::make_unique<RegisterApplicationCommands>();
		}

		void execute(BaseFunctionArguments& newArgs) {
			try {
				RespondToInputEventData dataPackage(newArgs.eventData);
				dataPackage.setResponseType(InputEventResponseType::Ephemeral_Deferred_Response);
				auto newEvent = InputEvents::respondToInputEventAsync(dataPackage).get();
				std::unique_ptr<Guild> guild = std::make_unique<Guild>(Guilds::getCachedGuildAsync({ .guildId = newArgs.eventData.getGuildId() }).get());
				DiscordGuild discordGuild{ *guild };

				std::unique_ptr<CreateGlobalApplicationCommandData> registerApplicationCommandsCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				registerApplicationCommandsCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				registerApplicationCommandsCommandData->dmPermission = false;
				registerApplicationCommandsCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				registerApplicationCommandsCommandData->description = "Register the programmatically designated slash commands.";
				registerApplicationCommandsCommandData->name = "registerapplicationcommands";
				registerApplicationCommandsCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*registerApplicationCommandsCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createSellDrugsCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createSellDrugsCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createSellDrugsCommandData->dmPermission = false;
				createSellDrugsCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createSellDrugsCommandData->description = "Sell drugs in exchange for some currency!";
				createSellDrugsCommandData->name = "selldrugs";
				createSellDrugsCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createSellDrugsCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createBalanceCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createBalanceCommandData->dmPermission = false;
				createBalanceCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createBalanceCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createBalanceCommandData->description = "Check your or another person's currency balances.";
				createBalanceCommandData->name = "balance";
				ApplicationCommandOptionData applicationCommandOptionOne;
				applicationCommandOptionOne.name = "person";
				applicationCommandOptionOne.required = false;
				applicationCommandOptionOne.type = ApplicationCommandOptionType::User;
				applicationCommandOptionOne.description = "The person who's balances you would like to check.";
				createBalanceCommandData->options.push_back(applicationCommandOptionOne);
				createBalanceCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createBalanceCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createAddShopItemCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createAddShopItemCommandData->dmPermission = false;
				createAddShopItemCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createAddShopItemCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createAddShopItemCommandData->description = "Add an item to the shop's inventory.";
				createAddShopItemCommandData->name = "addshopitem";
				ApplicationCommandOptionData addShopItemCommandOptionOne;
				addShopItemCommandOptionOne.name = "itemname";
				addShopItemCommandOptionOne.required = true;
				addShopItemCommandOptionOne.type = ApplicationCommandOptionType::String;
				addShopItemCommandOptionOne.description = "The name of the item.";
				createAddShopItemCommandData->options.push_back(addShopItemCommandOptionOne);
				ApplicationCommandOptionData addShopItemCommandOptionTwo;
				addShopItemCommandOptionTwo.name = "selfmod";
				addShopItemCommandOptionTwo.required = true;
				addShopItemCommandOptionTwo.type = ApplicationCommandOptionType::Integer;
				addShopItemCommandOptionTwo.description = "The self-mod value of the item.";
				addShopItemCommandOptionTwo.minValue = 0;
				addShopItemCommandOptionTwo.maxValue = 1000;
				createAddShopItemCommandData->options.push_back(addShopItemCommandOptionTwo);
				ApplicationCommandOptionData addShopItemCommandOptionThree;
				addShopItemCommandOptionThree.name = "oppmod";
				addShopItemCommandOptionThree.required = true;
				addShopItemCommandOptionThree.minValue = -1000;
				addShopItemCommandOptionThree.maxValue = 0;
				addShopItemCommandOptionThree.type = ApplicationCommandOptionType::Number;
				addShopItemCommandOptionThree.description = "The opp-mod value of the item.";
				createAddShopItemCommandData->options.push_back(addShopItemCommandOptionThree);
				ApplicationCommandOptionData addShopItemCommandOptionFour;
				addShopItemCommandOptionFour.name = "itemcost";
				addShopItemCommandOptionFour.required = true;
				addShopItemCommandOptionFour.type = ApplicationCommandOptionType::Integer;
				addShopItemCommandOptionFour.minValue = 0;
				addShopItemCommandOptionFour.maxValue = 100000000;
				addShopItemCommandOptionFour.description = "The value/cost of the item.";
				createAddShopItemCommandData->options.push_back(addShopItemCommandOptionFour);
				ApplicationCommandOptionData addShopItemCommandOptionFive;
				addShopItemCommandOptionFive.name = "emoji";
				addShopItemCommandOptionFive.required = true;
				addShopItemCommandOptionFive.type = ApplicationCommandOptionType::String;
				addShopItemCommandOptionFive.description = "The emoji/icon to use for the item.";
				createAddShopItemCommandData->options.push_back(addShopItemCommandOptionFive);
				createAddShopItemCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createAddShopItemCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createAddShopRoleCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createAddShopRoleCommandData->dmPermission = false;
				createAddShopRoleCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createAddShopRoleCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createAddShopRoleCommandData->description = "Add a role to the shop's inventory.";
				createAddShopRoleCommandData->name = "addshoprole";
				ApplicationCommandOptionData addShopRoleCommandOptionOne;
				addShopRoleCommandOptionOne.name = "rolename";
				addShopRoleCommandOptionOne.required = true;
				addShopRoleCommandOptionOne.type = ApplicationCommandOptionType::String;
				addShopRoleCommandOptionOne.description = "The name of the role.";
				createAddShopRoleCommandData->options.push_back(addShopRoleCommandOptionOne);
				ApplicationCommandOptionData addShopRoleCommandOptionTwo;
				addShopRoleCommandOptionTwo.name = "hexcolorvalue";
				addShopRoleCommandOptionTwo.required = true;
				addShopRoleCommandOptionTwo.type = ApplicationCommandOptionType::String;
				addShopRoleCommandOptionTwo.description = "The hex-color value of the role.";
				createAddShopRoleCommandData->options.push_back(addShopRoleCommandOptionTwo);
				ApplicationCommandOptionData addShopRoleCommandOptionThree;
				addShopRoleCommandOptionThree.name = "rolecost";
				addShopRoleCommandOptionThree.required = true;
				addShopRoleCommandOptionThree.minValue = 0;
				addShopRoleCommandOptionThree.maxValue = 10000000;
				addShopRoleCommandOptionThree.type = ApplicationCommandOptionType::Integer;
				addShopRoleCommandOptionThree.description = "The value/cost of the role.";
				createAddShopRoleCommandData->options.push_back(addShopRoleCommandOptionThree);
				createAddShopRoleCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createAddShopRoleCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createCoinflipRoleCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createCoinflipRoleCommandData->dmPermission = false;
				createCoinflipRoleCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createCoinflipRoleCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createCoinflipRoleCommandData->description = "Play heads or tails.";
				createCoinflipRoleCommandData->name = "coinflip";
				ApplicationCommandOptionData coinflipCommandOptionOne;
				coinflipCommandOptionOne.name = "betamount";
				coinflipCommandOptionOne.required = true;
				coinflipCommandOptionOne.type = ApplicationCommandOptionType::Integer;
				coinflipCommandOptionOne.minValue = 1;
				coinflipCommandOptionOne.maxValue = 100000000;
				coinflipCommandOptionOne.description = "The wager you would like to place.";
				createCoinflipRoleCommandData->options.push_back(coinflipCommandOptionOne);
				createCoinflipRoleCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createCoinflipRoleCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createBlackjackCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createBlackjackCommandData->dmPermission = false;
				createBlackjackCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createBlackjackCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createBlackjackCommandData->description = "Play a round of blackjack.";
				createBlackjackCommandData->name = "blackjack";
				ApplicationCommandOptionData blackJackCommandOptionOne;
				blackJackCommandOptionOne.name = "betamount";
				blackJackCommandOptionOne.minValue = 1;
				blackJackCommandOptionOne.maxValue = 100000000;
				blackJackCommandOptionOne.required = true;
				blackJackCommandOptionOne.type = ApplicationCommandOptionType::Integer;
				blackJackCommandOptionOne.description = "The amount which you would like to wager.";
				createBlackjackCommandData->options.push_back(blackJackCommandOptionOne);
				createBlackjackCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createBlackjackCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createButtonsCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createButtonsCommandData->dmPermission = false;
				createButtonsCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createButtonsCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createButtonsCommandData->description = "Test the buttons.";
				createButtonsCommandData->name = "buttons";
				createButtonsCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createButtonsCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createShopCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createShopCommandData->dmPermission = false;
				createShopCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createShopCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createShopCommandData->description = "Check out the server's shop!";
				createShopCommandData->name = "shop";
				createShopCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createShopCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createBotInfoCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createBotInfoCommandData->dmPermission = true;
				createBotInfoCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createBotInfoCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createBotInfoCommandData->description = "Displays info about the current bot.";
				createBotInfoCommandData->name = "botinfo";
				createBotInfoCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createBotInfoCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createCasinoStatsCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createCasinoStatsCommandData->dmPermission = false;
				createCasinoStatsCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createCasinoStatsCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createCasinoStatsCommandData->description = "View the server's casino stats.";
				createCasinoStatsCommandData->name = "casinostats";
				createCasinoStatsCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createCasinoStatsCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createDisplayGuildsDataCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createDisplayGuildsDataCommandData->dmPermission = true;
				createDisplayGuildsDataCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createDisplayGuildsDataCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createDisplayGuildsDataCommandData->description = "View the list of servers that this bot is in.";
				createDisplayGuildsDataCommandData->name = "displayguildsdata";
				createDisplayGuildsDataCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createDisplayGuildsDataCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createDuelCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createDuelCommandData->dmPermission = false;
				createDuelCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createDuelCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createDuelCommandData->description = "Challenge another server member do a duel.";
				createDuelCommandData->name = "duel";
				ApplicationCommandOptionData duelCommandOptionOne;
				duelCommandOptionOne.name = "challengetarget";
				duelCommandOptionOne.required = true;
				duelCommandOptionOne.type = ApplicationCommandOptionType::User;
				duelCommandOptionOne.description = "The individual you are challenging to a duel.";
				createDuelCommandData->options.push_back(duelCommandOptionOne);
				ApplicationCommandOptionData duelCommandOptionTwo;
				duelCommandOptionTwo.name = "betamount";
				duelCommandOptionTwo.required = true;
				duelCommandOptionTwo.type = ApplicationCommandOptionType::Integer;
				duelCommandOptionTwo.minValue = 1;
				duelCommandOptionTwo.maxValue = 1000000000;
				duelCommandOptionTwo.description = "The amount of the wager you are putting up.";
				createDuelCommandData->options.push_back(duelCommandOptionTwo);
				createDuelCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createDuelCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createGamehouseOptionsCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createGamehouseOptionsCommandData->dmPermission = false;
				createGamehouseOptionsCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createGamehouseOptionsCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createGamehouseOptionsCommandData->description = "View the options of this bot.";
				createGamehouseOptionsCommandData->name = "gamehouseoptions";
				createGamehouseOptionsCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createGamehouseOptionsCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createInventoryCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createInventoryCommandData->dmPermission = false;
				createInventoryCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createInventoryCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createInventoryCommandData->description = "Observe your inventory of items and roles.";
				createInventoryCommandData->name = "inventory";
				ApplicationCommandOptionData inventoryCommandOptionOne;
				inventoryCommandOptionOne.name = "user";
				inventoryCommandOptionOne.required = false;
				inventoryCommandOptionOne.type = ApplicationCommandOptionType::User;
				inventoryCommandOptionOne.description = "The user who's inventory you would like to view.";
				createInventoryCommandData->options.push_back(inventoryCommandOptionOne);
				createInventoryCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createInventoryCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createLeaderboardCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createLeaderboardCommandData->dmPermission = false;
				createLeaderboardCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createLeaderboardCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createLeaderboardCommandData->description = "View the server's currency leaderboard.";
				createLeaderboardCommandData->name = "leaderboard";
				createLeaderboardCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createLeaderboardCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createRemoveObjectCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createRemoveObjectCommandData->dmPermission = false;
				createRemoveObjectCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createRemoveObjectCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createRemoveObjectCommandData->description = "Remove an object or role from a user's inventory.";
				createRemoveObjectCommandData->name = "removeobject";
				ApplicationCommandOptionData testCommandOptionOne;
				testCommandOptionOne.name = "objectname";
				testCommandOptionOne.required = false;
				testCommandOptionOne.type = ApplicationCommandOptionType::String;
				testCommandOptionOne.description = "The object to be removed.";
				createRemoveObjectCommandData->options.push_back(testCommandOptionOne);
				ApplicationCommandOptionData testCommandOptionTwo;
				testCommandOptionTwo.name = "role";
				testCommandOptionTwo.required = false;
				testCommandOptionTwo.type = ApplicationCommandOptionType::Role;
				testCommandOptionTwo.description = "The role to be removed.";
				createRemoveObjectCommandData->options.push_back(testCommandOptionTwo);
				ApplicationCommandOptionData testCommandOptionThree;
				testCommandOptionThree.name = "user";
				testCommandOptionThree.required = false;
				testCommandOptionThree.type = ApplicationCommandOptionType::User;
				testCommandOptionThree.description = "The user to remove the object/role from.";
				createRemoveObjectCommandData->options.push_back(testCommandOptionThree);
				createRemoveObjectCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createRemoveObjectCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createRemoveShopItemCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createRemoveShopItemCommandData->dmPermission = false;
				createRemoveShopItemCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createRemoveShopItemCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createRemoveShopItemCommandData->description = "Remove an item from the server's shop.";
				createRemoveShopItemCommandData->name = "removeshopitem";
				ApplicationCommandOptionData removeShopItemOptionOne;
				removeShopItemOptionOne.name = "item";
				removeShopItemOptionOne.required = true;
				removeShopItemOptionOne.type = ApplicationCommandOptionType::String;
				removeShopItemOptionOne.description = "The item which you would like to remove.";
				createRemoveShopItemCommandData->options.push_back(removeShopItemOptionOne);
				createRemoveShopItemCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createRemoveShopItemCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createRemoveShopRoleCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createRemoveShopRoleCommandData->dmPermission = false;
				createRemoveShopRoleCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createRemoveShopRoleCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createRemoveShopRoleCommandData->description = "Remove a role from the server's shop.";
				createRemoveShopRoleCommandData->name = "removeshoprole";
				ApplicationCommandOptionData removeShopRoleOptionOne;
				removeShopRoleOptionOne.name = "role";
				removeShopRoleOptionOne.required = true;
				removeShopRoleOptionOne.type = ApplicationCommandOptionType::Role;
				removeShopRoleOptionOne.description = "The role which you would like to remove.";
				createRemoveShopRoleCommandData->options.push_back(removeShopRoleOptionOne);
				createRemoveShopRoleCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createRemoveShopRoleCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createRobCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createRobCommandData->dmPermission = false;
				createRobCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createRobCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createRobCommandData->description = "Rob a user for currency.";
				createRobCommandData->name = "rob";
				ApplicationCommandOptionData robOptionOne;
				robOptionOne.name = "user";
				robOptionOne.required = true;
				robOptionOne.type = ApplicationCommandOptionType::User;
				robOptionOne.description = "The user which you would like to rob.";
				createRobCommandData->options.push_back(robOptionOne);
				createRobCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createRobCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createRouletteCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createRouletteCommandData->dmPermission = false;
				createRouletteCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createRouletteCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createRouletteCommandData->description = "Start or bet on a game of roulette.";
				createRouletteCommandData->name = "roulette";
				ApplicationCommandOptionData rouletteOptionOne;
				rouletteOptionOne.name = "start";
				rouletteOptionOne.type = ApplicationCommandOptionType::Sub_Command;
				rouletteOptionOne.description = "Begins the roulette round.";
				createRouletteCommandData->options.push_back(rouletteOptionOne);
				ApplicationCommandOptionData rouletteOptionTwo;
				rouletteOptionTwo.name = "bet1";
				rouletteOptionTwo.type = ApplicationCommandOptionType::Sub_Command;
				rouletteOptionTwo.description = "Bet on an active game of roulette.";
				ApplicationCommandOptionData rouletteOptionTwoOh;
				rouletteOptionTwoOh.name = "amount";
				rouletteOptionTwoOh.description = "Enter the amount which you would like to bet";
				rouletteOptionTwoOh.required = true;
				rouletteOptionTwoOh.type = ApplicationCommandOptionType::Integer;
				rouletteOptionTwoOh.minValue = 1;
				rouletteOptionTwoOh.maxValue = 100000000;
				rouletteOptionTwo.options.push_back(rouletteOptionTwoOh);
				ApplicationCommandOptionData rouletteOptionTwoOne;
				rouletteOptionTwoOne.name = "type";
				rouletteOptionTwoOne.type = ApplicationCommandOptionType::String;
				rouletteOptionTwoOne.required = true;
				rouletteOptionTwoOne.description = "Choose the type of bet you would like to make.";
				ApplicationCommandOptionChoiceData choice01;
				choice01.name = "0";
				choice01.value = "0";
				rouletteOptionTwoOne.choices.push_back(choice01);
				ApplicationCommandOptionChoiceData choice02;
				choice02.name = "00";
				choice02.value = "00";
				rouletteOptionTwoOne.choices.push_back(choice02);
				ApplicationCommandOptionChoiceData choice03;
				choice03.name = "straight";
				choice03.value = "straight";
				rouletteOptionTwoOne.choices.push_back(choice03);
				ApplicationCommandOptionChoiceData choice04;
				choice04.name = "row";
				choice04.value = "row";
				rouletteOptionTwoOne.choices.push_back(choice04);
				ApplicationCommandOptionChoiceData choice05;
				choice05.name = "split";
				choice05.value = "split";
				rouletteOptionTwoOne.choices.push_back(choice05);
				ApplicationCommandOptionChoiceData choice06;
				choice06.name = "street";
				choice06.value = "street";
				rouletteOptionTwoOne.choices.push_back(choice06);
				ApplicationCommandOptionChoiceData choice07;
				choice07.name = "basket";
				choice07.value = "basket";
				rouletteOptionTwoOne.choices.push_back(choice07);
				ApplicationCommandOptionChoiceData choice08;
				choice08.name = "sixline";
				choice08.value = "sixline";
				rouletteOptionTwoOne.choices.push_back(choice08);
				ApplicationCommandOptionChoiceData choice09;
				choice09.name = "1stcolumn";
				choice09.value = "1stcolumn";
				rouletteOptionTwoOne.choices.push_back(choice09);
				ApplicationCommandOptionChoiceData choice10;
				choice10.name = "2ndcolumn";
				choice10.value = "2ndcolumn";
				rouletteOptionTwoOne.choices.push_back(choice10);
				rouletteOptionTwo.options.push_back(rouletteOptionTwoOne);
				ApplicationCommandOptionData rouletteOptionTwoTwo;
				rouletteOptionTwoTwo.name = "betoptions";
				rouletteOptionTwoTwo.description = "Bet options for select bet-types.";
				rouletteOptionTwoOne.required = false;
				rouletteOptionTwoTwo.type = ApplicationCommandOptionType::Integer;
				rouletteOptionTwoTwo.minValue = 1;
				rouletteOptionTwoTwo.maxValue = 100;
				rouletteOptionTwo.options.push_back(rouletteOptionTwoTwo);
				createRouletteCommandData->options.push_back(rouletteOptionTwo);
				ApplicationCommandOptionData rouletteOptionThree;
				rouletteOptionThree.name = "bet2";
				rouletteOptionThree.type = ApplicationCommandOptionType::Sub_Command;
				rouletteOptionThree.description = "Bet on an active game of roulette.";
				ApplicationCommandOptionData rouletteOptionThreeOh;
				rouletteOptionThreeOh.name = "amount";
				rouletteOptionThreeOh.description = "Enter the amount which you would like to bet";
				rouletteOptionThreeOh.required = true;
				rouletteOptionThreeOh.type = ApplicationCommandOptionType::Integer;
				rouletteOptionThreeOh.minValue = 1;
				rouletteOptionThreeOh.maxValue = 1000000000;
				rouletteOptionThree.options.push_back(rouletteOptionThreeOh);
				ApplicationCommandOptionData rouletteOptionThreeOne;
				rouletteOptionThreeOne.name = "type";
				rouletteOptionThreeOne.type = ApplicationCommandOptionType::String;
				rouletteOptionThreeOne.required = true;
				rouletteOptionThreeOne.description = "Choose the type of bet you would like to make.";
				ApplicationCommandOptionChoiceData choice11;
				choice11.name = "3rdcolumn";
				choice11.value = "3rdcolumn";
				rouletteOptionThreeOne.choices.push_back(choice11);
				ApplicationCommandOptionChoiceData choice12;
				choice12.name = "1stdozen";
				choice12.value = "1stdozen";
				rouletteOptionThreeOne.choices.push_back(choice12);
				ApplicationCommandOptionChoiceData choice13;
				choice13.name = "2nddozen";
				choice13.value = "2nddozen";
				rouletteOptionThreeOne.choices.push_back(choice13);
				ApplicationCommandOptionChoiceData choice14;
				choice14.name = "3rddozen";
				choice14.value = "3rddozen";
				rouletteOptionThreeOne.choices.push_back(choice14);
				ApplicationCommandOptionChoiceData choice15;
				choice15.name = "odd";
				choice15.value = "odd";
				rouletteOptionThreeOne.choices.push_back(choice15);
				ApplicationCommandOptionChoiceData choice16;
				choice16.name = "even";
				choice16.value = "even";
				rouletteOptionThreeOne.choices.push_back(choice16);
				ApplicationCommandOptionChoiceData choice17;
				choice17.name = "red";
				choice17.value = "red";
				rouletteOptionThreeOne.choices.push_back(choice17);
				ApplicationCommandOptionChoiceData choice18;
				choice18.name = "black";
				choice18.value = "black";
				rouletteOptionThreeOne.choices.push_back(choice18);
				ApplicationCommandOptionChoiceData choice19;
				choice19.name = "1to18";
				choice19.value = "1to18";
				rouletteOptionThreeOne.choices.push_back(choice19);
				ApplicationCommandOptionChoiceData choice20;
				choice20.name = "19to36";
				choice20.value = "19to36";
				rouletteOptionThreeOne.choices.push_back(choice20);
				rouletteOptionThree.options.push_back(rouletteOptionThreeOne);
				ApplicationCommandOptionData rouletteOptionThreeTwo;
				rouletteOptionThreeTwo.name = "betoptions";
				rouletteOptionThreeTwo.description = "Bet options for select bet-types.";
				rouletteOptionThreeTwo.required = false;
				rouletteOptionThreeTwo.type = ApplicationCommandOptionType::Integer;
				rouletteOptionThreeTwo.minValue = 1;
				rouletteOptionThreeTwo.maxValue = 100;
				rouletteOptionThree.options.push_back(rouletteOptionThreeTwo);
				createRouletteCommandData->options.push_back(rouletteOptionThree);
				createRouletteCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createRouletteCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createSetGameChannelCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createSetGameChannelCommandData->dmPermission = false;
				createSetGameChannelCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createSetGameChannelCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createSetGameChannelCommandData->description = "Sets the channels which you can play games in.";
				createSetGameChannelCommandData->name = "setgamechannel";
				ApplicationCommandOptionData createSetGameChannelOptionOne;
				createSetGameChannelOptionOne.type = ApplicationCommandOptionType::Sub_Command;
				createSetGameChannelOptionOne.name = "view";
				createSetGameChannelOptionOne.description = "View the currently enabled channels.";
				createSetGameChannelCommandData->options.push_back(createSetGameChannelOptionOne);
				ApplicationCommandOptionData createSetGameChannelOptionTwo;
				createSetGameChannelOptionTwo.type = ApplicationCommandOptionType::Sub_Command;
				createSetGameChannelOptionTwo.name = "add";
				createSetGameChannelOptionTwo.description = "Add a channel to the list of enabled channels.";
				createSetGameChannelCommandData->options.push_back(createSetGameChannelOptionTwo);
				ApplicationCommandOptionData createSetGameChannelOptionThree;
				createSetGameChannelOptionThree.type = ApplicationCommandOptionType::Sub_Command;
				createSetGameChannelOptionThree.name = "remove";
				createSetGameChannelOptionThree.description = "Remove a channel to the list of enabled channels.";
				createSetGameChannelCommandData->options.push_back(createSetGameChannelOptionThree);
				ApplicationCommandOptionData createSetGameChannelOptionFour;
				createSetGameChannelOptionFour.type = ApplicationCommandOptionType::Sub_Command;
				createSetGameChannelOptionFour.name = "purge";
				createSetGameChannelOptionFour.description = "Purges the list of channels for the server.";
				createSetGameChannelCommandData->options.push_back(createSetGameChannelOptionFour);
				createSetGameChannelCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createSetGameChannelCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createSetBalanceCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createSetBalanceCommandData->dmPermission = false;
				createSetBalanceCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createSetBalanceCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createSetBalanceCommandData->description = "Set the currency balance of yourself or another server member.";
				createSetBalanceCommandData->name = "setbalance";
				ApplicationCommandOptionData createSetBalanceOptionOne;
				createSetBalanceOptionOne.type = ApplicationCommandOptionType::Integer;
				createSetBalanceOptionOne.name = "amount";
				createSetBalanceOptionOne.required = true;
				createSetBalanceOptionOne.minValue = 0;
				createSetBalanceOptionOne.maxValue = 100000000;
				createSetBalanceOptionOne.description = "The amount to set the balance to.";
				createSetBalanceCommandData->options.push_back(createSetBalanceOptionOne);
				ApplicationCommandOptionData createBalanceOptionOne;
				createBalanceOptionOne.type = ApplicationCommandOptionType::String;
				createBalanceOptionOne.name = "balancetype";
				createBalanceOptionOne.description = "Which of the two balances to set.";
				createBalanceOptionOne.required = true;
				ApplicationCommandOptionChoiceData setBalancechoiceOne;
				setBalancechoiceOne.name = "wallet";
				setBalancechoiceOne.value = "wallet";
				ApplicationCommandOptionChoiceData setBalancechoiceTwo;
				setBalancechoiceTwo.name = "bank";
				setBalancechoiceTwo.value = "bank";
				createBalanceOptionOne.choices.push_back(setBalancechoiceOne);
				createBalanceOptionOne.choices.push_back(setBalancechoiceTwo);
				createSetBalanceCommandData->options.push_back(createBalanceOptionOne);
				ApplicationCommandOptionData createSetBalanceOptionThree;
				createSetBalanceOptionThree.name = "targetuser";
				createSetBalanceOptionThree.description = "The user who's balance you would like to set.";
				createSetBalanceOptionThree.required = false;
				createSetBalanceOptionThree.type = ApplicationCommandOptionType::User;
				createSetBalanceCommandData->options.push_back(createSetBalanceOptionThree);
				createSetBalanceCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createSetBalanceCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createSetBorderColorCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createSetBorderColorCommandData->dmPermission = false;
				createSetBorderColorCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createSetBorderColorCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createSetBorderColorCommandData->description = "Set the defaul color of borders.";
				createSetBorderColorCommandData->name = "setbordercolor";
				ApplicationCommandOptionData createSetBorderColoreOptionOne;
				createSetBorderColoreOptionOne.type = ApplicationCommandOptionType::String;
				createSetBorderColoreOptionOne.name = "botname";
				createSetBorderColoreOptionOne.description = "Which of the bots to change the setting on.";
				createSetBorderColoreOptionOne.required = true;
				ApplicationCommandOptionChoiceData setBorderColorchoiceOne;
				setBorderColorchoiceOne.name = "gamehouse";
				setBorderColorchoiceOne.value = "gamehouse";
				createSetBorderColoreOptionOne.choices.push_back(setBorderColorchoiceOne);
				createSetBorderColorCommandData->options.push_back(createSetBorderColoreOptionOne);
				ApplicationCommandOptionData createSetBorderColorOptionTwo;
				createSetBorderColorOptionTwo.type = ApplicationCommandOptionType::String;
				createSetBorderColorOptionTwo.name = "hexcolorvalue";
				createSetBorderColorOptionTwo.required = true;
				createSetBorderColorOptionTwo.description = "The hex-color-value to set the borders to.";
				createSetBorderColorCommandData->options.push_back(createSetBorderColorOptionTwo);
				createSetBorderColorCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createSetBorderColorCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createSlotsCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createSlotsCommandData->dmPermission = false;
				createSlotsCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createSlotsCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createSlotsCommandData->description = "Play a game of slots.";
				createSlotsCommandData->name = "slots";
				ApplicationCommandOptionData createSlotsOptionOne;
				createSlotsOptionOne.type = ApplicationCommandOptionType::Integer;
				createSlotsOptionOne.minValue = 1;
				createSlotsOptionOne.maxValue = 100000000;
				createSlotsOptionOne.name = "betamount";
				createSlotsOptionOne.description = "The amount of currency which you will wager.";
				createSlotsOptionOne.required = true;
				createSlotsCommandData->options.push_back(createSlotsOptionOne);
				createSlotsCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createSlotsCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createTransferCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createTransferCommandData->dmPermission = false;
				createTransferCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createTransferCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createTransferCommandData->description = "Transfer currency from yourself to another server member.";
				createTransferCommandData->name = "transfer";
				ApplicationCommandOptionData createTransferOptionOne;
				createTransferOptionOne.type = ApplicationCommandOptionType::Integer;
				createTransferOptionOne.minValue = 1;
				createTransferOptionOne.maxValue = 1000000000;
				createTransferOptionOne.name = "amount";
				createTransferOptionOne.description = "The amount of currency which you would like to transfer.";
				createTransferOptionOne.required = true;
				createTransferCommandData->options.push_back(createTransferOptionOne);
				ApplicationCommandOptionData createTransferOptionTwo;
				createTransferOptionTwo.type = ApplicationCommandOptionType::User;
				createTransferOptionTwo.name = "user";
				createTransferOptionTwo.description = "The target user for the transfer.";
				createTransferOptionTwo.required = true;
				createTransferCommandData->options.push_back(createTransferOptionTwo);
				createTransferCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createTransferCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createWithdrawCommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createWithdrawCommandData->dmPermission = false;
				createWithdrawCommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createWithdrawCommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createWithdrawCommandData->description = "Withdraw currency from your bank account to your wallet.";
				createWithdrawCommandData->name = "withdraw";
				ApplicationCommandOptionData createWithdrawOptionOne;
				createWithdrawOptionOne.type = ApplicationCommandOptionType::Integer;
				createWithdrawOptionOne.minValue = 1;
				createWithdrawOptionOne.maxValue = 10000000000;
				createWithdrawOptionOne.name = "amount";
				createWithdrawOptionOne.description = "The amount of currency which you would like to withdraw.";
				createWithdrawOptionOne.required = true;
				createWithdrawCommandData->options.push_back(createWithdrawOptionOne);
				createWithdrawCommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createWithdrawCommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createDepositommandData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createDepositommandData->dmPermission = false;
				createDepositommandData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createDepositommandData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createDepositommandData->description = "Deposit currency from your wallet into your bank.";
				createDepositommandData->name = "deposit";
				ApplicationCommandOptionData createDepositOptionOne;
				createDepositOptionOne.type = ApplicationCommandOptionType::Integer;
				createDepositOptionOne.minValue = 1;
				createDepositOptionOne.maxValue = 10000000000;
				createDepositOptionOne.name = "amount";
				createDepositOptionOne.description = "The amount of currency which you would like to deposit.";
				createDepositOptionOne.required = true;
				createDepositommandData->options.push_back(createDepositOptionOne);
				createDepositommandData->type = ApplicationCommandType::Chat_Input;
				ApplicationCommands::createGlobalApplicationCommandAsync(*createDepositommandData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createHelpData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createHelpData->dmPermission = true;
				createHelpData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createHelpData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createHelpData->type = ApplicationCommandType::Chat_Input;
				createHelpData->description = "Get help with this bot's commands.";
				createHelpData->name = "help";
				ApplicationCommands::createGlobalApplicationCommandAsync(*createHelpData);

				std::unique_ptr<CreateGlobalApplicationCommandData> createTestData{ std::make_unique<CreateGlobalApplicationCommandData>() };
				createTestData->dmPermission = true;
				createTestData->applicationId = newArgs.discordCoreClient->getBotUser().id;
				createTestData->type = ApplicationCommandType::Chat_Input;
				createTestData->name = "test";
				createTestData->defaultMemberPermissions = std::to_string(static_cast<int64_t>(Permission::Use_Application_Commands));
				createTestData->description = "Test command.";
				ApplicationCommands::createGlobalApplicationCommandAsync(*createTestData);

				std::unique_ptr<EmbedData> msgEmbed{ std::make_unique<EmbedData>() };
				msgEmbed->setAuthor(newArgs.eventData.getUserName(), newArgs.eventData.getAvatarUrl());
				msgEmbed->setColor("FeFeFe");
				msgEmbed->setDescription("------\nNicely done, you've registered some commands!\n------");
				msgEmbed->setTimeStamp(getTimeAndDate());
				msgEmbed->setTitle("__**Register Application Commands Complete:**__");
				std::unique_ptr<RespondToInputEventData> responseData{ std::make_unique<RespondToInputEventData>(newEvent) };
				responseData->setResponseType(InputEventResponseType::Edit_Interaction_Response);
				responseData->addMessageEmbed(*msgEmbed);
				auto event = InputEvents::respondToInputEventAsync(*responseData).get();
				return;
			} catch (...) {
				reportException("RegisterApplicationCommands::execute()");
			}
		}
		~RegisterApplicationCommands(){};
	};
}
