function(findopenssl RELEASE_ROOT_DIR DEBUG_ROOT_DIR)
	find_library(LIBCRYPTO_RELEASE_LIBRARY NAME "libcrypto${LIBRARY_SUFFIX}" PATHS "${RELEASE_ROOT_DIR}")
	find_library(LIBCRYPTO_DEBUG_LIBRARY NAME "libcrypto${LIBRARY_SUFFIX}" PATHS "${DEBUG_ROOT_DIR}")	
	find_library(LIBSSL_RELEASE_LIBRARY NAME "libssl${LIBRARY_SUFFIX}" PATHS "${RELEASE_ROOT_DIR}")
	find_library(LIBSSL_DEBUG_LIBRARY NAME "libssl${LIBRARY_SUFFIX}" PATHS "${DEBUG_ROOT_DIR}")	
	if (EXISTS "${LIBSSL_RELEASE_LIBRARY}" AND EXISTS "${LIBSSL_DEBUG_LIBRARY}" AND EXISTS "${LIBCRYPTO_RELEASE_LIBRARY}" AND EXISTS "${LIBCRYPTO_DEBUG_LIBRARY}")
        add_library(LIBCRYPTO UNKNOWN IMPORTED GLOBAL)
        add_library(OpenSSL::Crypto ALIAS LIBCRYPTO)
        set_target_properties(LIBCRYPTO PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            IMPORTED_LOCATION "${LIBCRYPTO_RELEASE_LIBRARY}")
        set_property(TARGET LIBCRYPTO APPEND PROPERTY
            IMPORTED_CONFIGURATIONS RELEASE)
            set_target_properties(LIBCRYPTO PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
            IMPORTED_LOCATION_RELEASE "${LIBCRYPTO_RELEASE_LIBRARY}")
        set_property(TARGET LIBCRYPTO APPEND PROPERTY
            IMPORTED_CONFIGURATIONS DEBUG)
            set_target_properties(LIBCRYPTO PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
            IMPORTED_LOCATION_DEBUG "${LIBCRYPTO_DEBUG_LIBRARY}")

        add_library(LIBSSL UNKNOWN IMPORTED GLOBAL)
        add_library(OpenSSL::SSL ALIAS LIBSSL)
        set_target_properties(LIBSSL PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            IMPORTED_LOCATION "${LIBSSL_RELEASE_LIBRARY}")
        set_property(TARGET LIBSSL APPEND PROPERTY
            IMPORTED_CONFIGURATIONS RELEASE)
            set_target_properties(LIBSSL PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
            IMPORTED_LOCATION_RELEASE "${LIBSSL_RELEASE_LIBRARY}")
        set_property(TARGET LIBSSL APPEND PROPERTY
            IMPORTED_CONFIGURATIONS DEBUG)
            set_target_properties(LIBSSL PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
            IMPORTED_LOCATION_DEBUG "${LIBSSL_DEBUG_LIBRARY}")
        target_link_libraries(LIBSSL INTERFACE LIBCRYPTO)
        message(STATUS "Found OpenSSL!")
	else()
		message(FATAL_ERROR "Couldn't find OpenSSL!")
	endif()
endfunction()