function(findffmpeg RELEASE_ROOT_DIR DEBUG_ROOT_DIR)
find_library(AVCODEC_RELEASE_LIBRARY NAME "${LIBRARY_PREFIX}avcodec${LIBRARY_SUFFIX}" PATHS "${RELEASE_ROOT_DIR}")
	find_library(AVCODEC_DEBUG_LIBRARY NAME "${LIBRARY_PREFIX}avcodec${LIBRARY_SUFFIX}" PATHS "${DEBUG_ROOT_DIR}")
	find_library(AVFORMAT_RELEASE_LIBRARY NAME "${LIBRARY_PREFIX}avformat${LIBRARY_SUFFIX}" PATHS "${RELEASE_ROOT_DIR}")
	find_library(AVFORMAT_DEBUG_LIBRARY NAME "${LIBRARY_PREFIX}avformat${LIBRARY_SUFFIX}" PATHS "${DEBUG_ROOT_DIR}")
	find_library(AVUTIL_RELEASE_LIBRARY NAME "${LIBRARY_PREFIX}avutil${LIBRARY_SUFFIX}" PATHS "${RELEASE_ROOT_DIR}")
	find_library(AVUTIL_DEBUG_LIBRARY NAME "${LIBRARY_PREFIX}avutil${LIBRARY_SUFFIX}" PATHS "${DEBUG_ROOT_DIR}")	
	find_library(SWRESAMPLE_RELEASE_LIBRARY NAME "${LIBRARY_PREFIX}swresample${LIBRARY_SUFFIX}" PATHS "${RELEASE_ROOT_DIR}")
	find_library(SWRESAMPLE_DEBUG_LIBRARY NAME "${LIBRARY_PREFIX}swresample${LIBRARY_SUFFIX}" PATHS "${DEBUG_ROOT_DIR}")
	if (EXISTS "${AVFORMAT_RELEASE_LIBRARY}" AND EXISTS "${AVFORMAT_DEBUG_LIBRARY}" AND EXISTS "${SWRESAMPLE_RELEASE_LIBRARY}" AND EXISTS "${SWRESAMPLE_DEBUG_LIBRARY}" AND EXISTS "${AVCODEC_RELEASE_LIBRARY}"
		AND EXISTS "${AVCODEC_DEBUG_LIBRARY}" AND EXISTS "${AVUTIL_RELEASE_LIBRARY}" AND EXISTS "${AVUTIL_DEBUG_LIBRARY}")
		add_library(AVCodec UNKNOWN IMPORTED GLOBAL)
        add_library(FFMPEG::AVCodec ALIAS AVCodec)
        set_target_properties(AVCodec PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            IMPORTED_LOCATION "${AVCODEC_RELEASE_LIBRARY}")
        set_property(TARGET AVCodec APPEND PROPERTY
            IMPORTED_CONFIGURATIONS RELEASE)
        set_target_properties(AVCodec PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
            IMPORTED_LOCATION_RELEASE "${AVCODEC_RELEASE_LIBRARY}")
        set_property(TARGET AVCodec APPEND PROPERTY
            IMPORTED_CONFIGURATIONS DEBUG)
        set_target_properties(AVCodec PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
            IMPORTED_LOCATION_DEBUG "${AVCODEC_DEBUG_LIBRARY}") 
	    add_library(AVFormat UNKNOWN IMPORTED GLOBAL)
        add_library(FFMPEG::AVFormat ALIAS AVFormat)
        set_target_properties(AVFormat PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            IMPORTED_LOCATION "${AVFORMAT_RELEASE_LIBRARY}")
        set_property(TARGET AVFormat APPEND PROPERTY
            IMPORTED_CONFIGURATIONS RELEASE)
        set_target_properties(AVFormat PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
            IMPORTED_LOCATION_RELEASE "${AVFORMAT_RELEASE_LIBRARY}")
        set_property(TARGET AVFormat APPEND PROPERTY
            IMPORTED_CONFIGURATIONS DEBUG)
        set_target_properties(AVFormat PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
            IMPORTED_LOCATION_DEBUG "${AVFORMAT_DEBUG_LIBRARY}") 
        add_library(AVUtil UNKNOWN IMPORTED GLOBAL)
        add_library(FFMPEG::AVUtil ALIAS AVUtil)
        set_target_properties(AVUtil PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            IMPORTED_LOCATION "${AVUTIL_RELEASE_LIBRARY}")
        set_property(TARGET AVUtil APPEND PROPERTY
            IMPORTED_CONFIGURATIONS RELEASE)
        set_target_properties(AVUtil PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
            IMPORTED_LOCATION_RELEASE "${AVUTIL_RELEASE_LIBRARY}")
        set_property(TARGET AVUtil APPEND PROPERTY
            IMPORTED_CONFIGURATIONS DEBUG)
        set_target_properties(AVUtil PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
            IMPORTED_LOCATION_DEBUG "${AVUTIL_DEBUG_LIBRARY}") 
        add_library(SWResample UNKNOWN IMPORTED GLOBAL)
        add_library(FFMPEG::SWResample ALIAS SWResample)
        set_target_properties(SWResample PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES "C"
            IMPORTED_LOCATION "${SWRESAMPLE_RELEASE_LIBRARY}")
        set_property(TARGET SWResample APPEND PROPERTY
            IMPORTED_CONFIGURATIONS RELEASE)
        set_target_properties(SWResample PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
            IMPORTED_LOCATION_RELEASE "${SWRESAMPLE_RELEASE_LIBRARY}")
        set_property(TARGET SWResample APPEND PROPERTY
            IMPORTED_CONFIGURATIONS DEBUG)
        set_target_properties(SWResample PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
            IMPORTED_LOCATION_DEBUG "${SWRESAMPLE_DEBUG_LIBRARY}")
		message(STATUS "Found FFMPEG!")
	else()
		message(FATAL_ERROR "Couldn't find FFMPEG!")
	endif()
endfunction()